### ISSUE TITLE
Container makes use of methods not in ConfigInterface

### ISSUE THREAD

**Issue by weierophinney** [auraphp/Aura.Di#1]
The container's constructor retrieves the configuration object from the Forge object passed to it. It then calls two methods on that object: getParams() and getSetter(). However, these two methods are not defined in ConfigInterface -- which means that if a developer were to write their own ConfigInterface implementation and not include those methods, the Container would raise fatal errors.

Either these methods should be added to the ConfigInterface, or not relied upon within the Container implementation.

**Comment by auraphp** [comment]
Good call. Will define them. I'm sure there is other similar interface inattention; please point it out when you see it.  Thanks!

**Comment by auraphp** [comment]
Fixed in https://github.com/auraphp/aura.di/commit/7c8cdcfe5d5bac89e1ff65b35259d9847602bac1
