### ISSUE TITLE
Tag request

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Di#108]
@pmjones Could you tag the latest changes in the 2.x branch? I am having the same IDE problems. They would be solved by a simple tag. Moreover, as development is now focussed on 3.x, I think it would be a pity if final 2.x changes do not end up in a release.

**Comment by harikt** [comment]
@frederikbosch sorry for the delay.

Working on making a release. Hope we can do this soon.

**Comment by frederikbosch** [comment]
:+1: That would be great!

**Comment by pmjones** [comment]
Done, as 2.2.4. :-)
