### ISSUE TITLE
tests and .gitattributes

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Di#111]
@harikt mentioned this on 2c0f7d1 already, but it wasn't clear to me that this was actually dealt with, so I'm raising it here. Apologies if this is poor form.

Test and docs are removed from the distribution.

I believe composer has stopped advocating this composer/composer@bf32869

I also believe others have ceased this or reverted this behavior as well:
symfony/symfony#6605

With this package specifically, I find that the `AbstractContainerConfigTest` test class is useful if I'm writing a package that integrates with Aura\Di. (Perhaps relying on that is poor form, but it's nice for now at least).

If I include `perfer-stable` in my composer.json, that I won't get the tests by default as it stands.

In the interim, I have simply added `--perfer-source` when deploying for development or testing (eg. `travis.yaml`) and my testing dependencies work fine. I thought I would raise this anyway, for clarity.

**Comment by harikt** [comment]
Thank you for all the references @jakejohns .

**Comment by pmjones** [comment]
I have removed the .gitattributes file that excludes the tests and docs (and other stuff). I'm stopping the practice in other packages as well. Thanks for pointing this out!
