### ISSUE TITLE
[v3] Can't get setter injection to work

### ISSUE THREAD

**Issue by glen-84** [auraphp/Aura.Di#112]
I've tried:

``` php
// Parent class.
$di->setters[BaseController::class]['setView'] = $di->lazyNew(ExpressiveExtensions\View::class);
```

``` php
// Sub class.
$di->setters[SiteController::class]['setView'] = $di->lazyNew(ExpressiveExtensions\View::class);
```

``` php
// Direct instance.
$di->setters[BaseController::class]['setView'] = new ExpressiveExtensions\View();
```

etc., and it doesn't appear to be working.

I hope that I'm not missing something obvious. :worried:

**Comment by glen-84** [comment]
I think this has something to do with the Zend Expressive dispatcher – ignore for now.

**Comment by glen-84** [comment]
Okay, so the issue is that ZE uses `$container->has()`, and since I'm using automatic resolution, it most-likely returns `false` when checking for a controller. This probably falls back to manual construction, which means that setter injection does not take place.

Solutions:
1. Manual configuration – I'm switching to Aura.Di in order to use auto-resolution, so this is not ideal at all.
   - Is there some way to tell Aura.Di that it _is_ capable of constructing certain objects, so that it would return `true`? I doubt it.
   - I wonder if `has()` is supposed to return `true` in the case of auto-resolution. The phpDoc comment says:
     - `has($id)` returning true does not mean that `get($id)` will not throw an exception.
     - It does however mean that `get($id)` will not throw a `NotFoundException`.
   - It might fail because of a missing param ... which is not the same as a `NotFoundException`. IDK.
2. Write a custom dispatcher that uses `$container->get()` instead of `has()` – I plan to write a custom dispatcher anyway, but I'm not sure what this will look like. It seems dirty to get an exception when calling `get()` ... it would be nice if it was something like `get($id, $default = null)`.

I'm a bit stuck. :confused:

**Comment by harikt** [comment]
Hi @glen-84 , 

not sure if this is related, but could you try changing the `BaseController::class` with string?

So it will look as `BaseController` , if there is namespace please do add. I doubt something ... ;) .

Thank you.

**Comment by glen-84** [comment]
@harikt `BaseController::class` _is_ a string (`=== 'ExpressiveExtensions\\BaseController'`)

The solution is in [this PR](https://github.com/container-interop/container-interop/pull/65). I'm hoping that if it's accepted (in principle), that @pmjones will consider including the change in Aura.Di 3.0.

**Comment by harikt** [comment]
@glen-84 iirc when I tried with `::class` in the di params itself it didn't worked as I expected. I didn't checked further the cause though I didn't have enough time. But my belief is a single change in name for the di will fail to get the service.

**Comment by glen-84** [comment]
@harikt It's not that, the problem is that `has` doesn't return true when you're using auto-resolution (see the above-mentioned PR).

**Comment by harikt** [comment]
So I hope this is not an issue with Aura.Di as mentioned `setter injection not working`

**Comment by glen-84** [comment]
@harikt It's not really an issue with Aura.Di. I'll close this and open a new issue if/when there is a solution that can be implemented. Thanks.
