### ISSUE TITLE
[v3] No auto-resolution with $container->get?

### ISSUE THREAD

**Issue by glen-84** [auraphp/Aura.Di#116]
All this time I've been assuming that I would be able to do something like `$container->get('My\Controller')` and it would "just work". Testing it now, and I get a `ServiceNotFound` exception. :disappointed:

Why isn't this part supported?

**Comment by harikt** [comment]
Thank you @glen-84 for the report.

**Comment by pmjones** [comment]
Hi @glen-84 -- have you defined a service named "My\Controller"? (Note that service names are independent of class names.)

**Comment by glen-84** [comment]
@pmjones No, I thought that the whole point of automatic resolution was that you _didn't_ need to define services. =)

I think that's how PHP-DI works ([link](http://php-di.org/doc/autowiring.html)), but I haven't yet tested it, as I was hoping to avoid moving to a 3rd DI container.

**Comment by pmjones** [comment]
It's automatic "resolution", not automatic "definition". If what you need is a new _class_ instance, then you would use `newInstance()`, not `get()`.

What am I missing from your question?

**Comment by glen-84** [comment]
I guess I misunderstood what `get` does. But this now means that I can't create a controller using methods from the container-interop interface, so my code becomes dependent on a specific implementation. :disappointed:

I don't know if it's worth suggesting standardization for `newInstance`/[make](http://php-di.org/doc/container.html#make).

I think I'll test PHP-DI's `get` method, because I'm not 100% certain that it behaves the same way.

**Comment by harikt** [comment]
Hey @glen-84 , 

I just made a branch, probably that should work. I still need to write some tests and all. Just a quick fix type. Let me know what you think if you have time.

**Comment by glen-84** [comment]
@pmjones I just tested PHP-DI and it doesn't require any definition before calling `get`. I think that it might be best if both libraries have the same behaviour. Which one should change is up to you guys.

@harikt That looks like it will throw an exception anyway on line 294. Also I'm not sure about the exception handling (whether it should catch everything and throw ServiceNotFound, etc.)

**Comment by glen-84** [comment]
@harikt

PHP-DI's behaviour, just for interest's sake:

Class doesn't exist:

`DI\NotFoundException: No entry or class found for 'X\UserManagerx'`

Class has unresolvable parameter (no type hint):

`DI\Definition\Exception\DefinitionException: Entry "X\UserManager" cannot be resolved: Parameter $x of __construct() has no value defined or guessable`

**Comment by harikt** [comment]
@glen-84 I pushed a fix. I know there probably need more tests. Busy day :-)

**Comment by harikt** [comment]
@pmjones do you have any issues with auto registering the service based on the class names ?

**Comment by glen-84** [comment]
@pmjones I'm going to need to make a decision soon about whether I switch containers again, or wait for a solution here. Is this likely to happen any time soon?

**Comment by harikt** [comment]
@glen-84 FYI  : Paul seems to be travelling. See status https://twitter.com/pmjones/status/699596686146928640 .

**Comment by glen-84** [comment]
@harikt Thanks for the info.

**Comment by harikt** [comment]
By the way @glen-84 : In the mean time can you make sure does #119 help you resolve the same ?

**Comment by harikt** [comment]
and FYI : If auraphp doesnot provide this functionality in core, extend the `Aura\Di\Container` class and modify the `has` method as in https://github.com/harikt/Aura.Di/blob/9c0c5dbbda619e83b4c1f828ab690339981420d1/src/Container.php#L202-L224 . You are all good to go.

Hope that helps you, not to switch more containers ;-) .

Thank you

**Comment by glen-84** [comment]
@harikt I was just testing `newInstance` and it seems that it doesn't do what I expected either.

The class is type-hinted with an interface, but it will throw a missing param exception unless you explicitly map the interface using `$di->types[Interface::class] = $di->lazyGet(Interface::class)`. In other words, it doesn't check if the container is able to supply that dependency.

This is in `AutoResolver#getUnifiedParam`. Maybe I'm expecting too much, and maybe supporting this is too magical and prone to issues. I'm not sure yet.

**Comment by glen-84** [comment]
I just tested PHP-DI and it behaves the way that I expected. It looks like I may have to switch containers again. :disappointed:

**Comment by harikt** [comment]
> The class is type-hinted with an interface, but it will throw a missing param exception unless you explicitly map the interface using `$di->types[Interface::class] = $di->lazyGet(Interface::class)` . In other words, it doesn't check if the container is able to supply that dependency.

Isn't that an expected behaviour?

How does the container will know which class need to be provided to the interface without type defining it?

If not an example or PR to show a failing test will be helpful.

Thank you

**Comment by glen-84** [comment]
> Isn't that an expected behaviour?

No, not when I've already done `$di->set(Interface::class, ...)`, and `get` will return an instance.

**Comment by harikt** [comment]
Oh oh oh.. you are setting interface as a service :-/ . See https://github.com/auraphp/Aura.Di/blob/3.x/docs/auto.md#auto-resolving-from-abstract-and-interface-typehints .  The implementation may differ from containers to containers.

I understand where the concept is coming, expressive and zend-service manager do something like this. I don't know / can comment more on this. May be may be not :) .

**Comment by glen-84** [comment]
Ya, and I've just learned that PHP-DI doesn't support setter calls on parent classes, so ... :man::gun:

**Comment by harikt** [comment]
I believe now you would have enough information to write a comparison blog post regarding different di containers :-) . And my belief is that probably set for interfaces can also be achievable. I haven't looked more or unsure if @pmjones like the idea.

**Comment by glen-84** [comment]
> And my belief is that probably set for interfaces can also be achievable.

I'm not sure what you mean here. It's already possible to set the implementation for an interface. The problem is that `newInstance` doesn't make use of it.

**Comment by harikt** [comment]
ok. Thanks.

Can you make another issue for the same ?

Thank you.

**Comment by pmjones** [comment]
I think I see an underlying issue, one of expectations; that is, @glen-84 expects that a "service name" is presumed to be a "class name." For Aura.Di, this is not the case; service names are not class names. You can choose to use a service name that looks like a class name, but the container will not honor it as such.

I get that lots of other container systems use "service names" and "class names" interchangeably. In my opinion, it is a mistake to do so. The moment you need two services of the same class, that busts the naming convention.

@glen-84 Do you see what I'm getting at here?

**Comment by harikt** [comment]
Hey @pmjones ,

> The moment you need two services of the same class, that busts the naming convention

Probably I didn't completely get you here. 

Doesn't that mean the user can define it for such cases as we are doing?

``` php
$di->set('service1', $di->lazyNew('ParentClass'));
$di->set('service2', $di->lazyNew('ParentClass'));

$di->get('service1');
$di->get('service2');
```

In the auto wiring, if the user don't care about naming service that means he should expect the same object. Right ? 

In the above example `service1` and `service2` will create different objects.

Or are you talking about a different example ?

Thank you

**Comment by pmjones** [comment]
@harikt Yes, exactly. For another example, two PDO connections to two different database systems:

```
$di->set('pdo-1', function () {
    return new PDO('mysql:foo.example.com...');
});

$di->set('pdo-2', function () {
    return new PDO('mysql:bar.example.net...');
});
```

If you use a "class name" as the "service name" then there's no way to set up shared services that are different instances of the same class.

**Comment by harikt** [comment]
@pmjones I will probably say that is not a big deal for most / common cases will be using one service. But as we can set the service as you mentioned, it seems not a big concern to me.

**Comment by pmjones** [comment]
/me ponders

I admit I am not a fan of the idea of making service names interchangeable with class names, and certainly not of making get() create a service instance automatically. Everyone else seems to do it, though, and as you state @harikt it is not the common case to need two services of the same class (well, it was common for me on one project, and so it lives on here).

**Comment by glen-84** [comment]
> @glen-84 expects that a "service name" is presumed to be a "class name."

Not exactly. I expect(ed) that if there is no service registered with that name, the behaviour of auto-resolution would be to instantiate the class if it existed.

If we assume that this is wrong, then I am left in a position where I cannot get a service from the container using auto-wiring/resolution without using a "non-standard" method (`newInstance`/`make`/`whatever`).

And not only that, but `has` and `get` behave completely differently between containers, so container-interop is mostly pointless.

https://github.com/container-interop/container-interop/issues/44 might be relevant.

:worried:

**Comment by pmjones** [comment]
Further, the use case here seems to be "inject the Container so that I can get any class out of it I want as a shared instance." (Yes, "any class" in this case is "a controller", but once you do it for one type of object, it's going to work for any type of object.) That's not something I want to encourage.

It seems more like that what @glen-84 really wants is a Factory to create a class instance when needed, not a Container that stores shared instances.

I wonder @glen-84 if it would be enough to add the Container-Interop methods to the underlying Aura\Di\Injection\Factory object? Then you can inject _that_ into your dispatcher system, and use it to get new instances of whatever you like.

**Comment by pmjones** [comment]
Or to create a separate Factory object alongside the Container, whose only job is to create new instances.

**Comment by harikt** [comment]
@glen-84 basically container inter-operability doesn't define what the identifier is. So I believe you cannot say it is wrong. See https://github.com/container-interop/container-interop/blob/2e7d7d62d7c78c00ad2a33a1c4698d81a1dea7ea/src/Interop/Container/ContainerInterface.php#L19

**Comment by pmjones** [comment]
I'm not saying "Container-Interop is wrong," I'm saying "I think it's a mistake to conflate service names with class names." :-)

**Comment by harikt** [comment]
by the way to add, autowiring is a capability of di containers, not interoperability. If we need real di container interoperability we need more methods and defintions ;) .

**Comment by koriym** [comment]
Hi, All.

@pmjones Do you have a any suggested "service name" convention instead of class name ?

**Comment by pmjones** [comment]
My own convention has been "vendor/package:service_name". That deconflicts between different packages, even from the same vendor, and allows arbitrary service names thereafter. It's also easy to search for in the config code, to see where it gets defined.

**Comment by koriym** [comment]
@pmjones I see. Thank you.

**Comment by glen-84** [comment]
@pmjones,

The use case is to create controllers, and have their dependencies injected without having to configure anything.

I hear you WRT using a factory instead of the container, but I need the DI, and I would really like that to be container-interop compatible, so would the solution be to standardize on the container's factory method? (newInstance/make/create/build/etc.) [see https://github.com/container-interop/container-interop/issues/44]

My head will explode in 3 ... 2 ... 1 ... =)

**Comment by harikt** [comment]
> It's also easy to search for in the config code, to see where it gets defined.

That is a good point @pmjones .

So many people promoting naming things as class .. See https://twitter.com/GeeH/status/697021897775718401 . Not sure how we can stop the usage of class names named as a service.

**Comment by pmjones** [comment]
OK @glen-84 here's the plan:

I'm going to create a new class, `InstanceFactory`, that implements container-interop. Each call to get() will create and return a new instance of the named class, using the params/setters/etc. that have been configured in the Container. Each call to has() will essentially return the results of class_exists(). I'll create it in a new branch and submit it to you for review, and you can tell me if it suits your needs. If it does we can work from there; if not we can go back to formula.

Sound reasonable?

**Comment by glen-84** [comment]
Can that replace the regular container? I mean, will the other functionality still be there?

It feels weird. I know I'm strange, but I'd prefer to do something that is standardized. So PHP-DI supports creation via `get`, and now Aura, but what if I switch to Banana.Di, and because there is nothing about this in container-interop, it doesn't support it.

I feel like one of two things needs to happen:
1. container-interop requires that `get` supports creation when auto-wiring is enabled (and `has` behaves appropriately).
2. container-interop standardizes on a factory method as part of the main container interface.

After your input above, I'm starting to migrate towards the second option, but of course standardization could take months, which would mean that I would need to hard-code a work-around in the meantime. Maybe not the end of the world.

I am very appreciative of your & @harikt's assistance in this matter, but I just want to make sure that things are done in the most compatible way.

**Comment by pmjones** [comment]
> Can that replace the regular container? I mean, will the other functionality still be there?

What I envision is that you would still do all setup through the regular $di container, but when you have a class that needs an InstanceFactory, you would pass $di->newInstanceFactory() to it. The InstanceFactory::get() method I expect will only be a proxy to the $di->newInstance() call, so all the other container configuration features will be honored, just not available to whatever is calling InstanceFactory::get().

> After your input above, I'm starting to migrate towards the second option, but of course standardization could take months, which would mean that I would need to hard-code a work-around in the meantime. Maybe not the end of the world.

I understand your desire for compatibility. I too would like to see a container-interop `newInstance()` method (please for the love of all that is good, not `make()`). Perhaps the thing to do here is lobby the container-interop folk to add a newInstance() method to a 2.0 version of the interface. I must warn, though, that I expect it to be a difficult process, as creating a new instance is a relative complex thing (more complex than you may realize).

**Comment by harikt** [comment]
@pmjones I don't know if your suggestion is related. But this was a difficulty that I faced recently. May be your suggestion seems to work the way for me, but I am still not sure on it though.

This is how I did 

``` php
<?php
namespace Hkt\_Config;

use League\OAuth2\Client\Provider\Github;

class OauthProviderFactory
{
    public function newInstance($provider)
    {
        switch ($provider) {
            case 'github':
                $provider = new Github(array(
                    'clientId' => 'fdff',
                    'clientSecret' => 'dffdfd',
                    'redirectUri' => 'http://expressive-skelton/login/github'
                ));
                break;
            default:
                throw new \Exception('No such provider registered');
                break;
        }

        return $provider;
    }
}
```

and `Action` class.

``` php
class OauthLoginAction
{
    public function __construct(
        Auth $auth,
        LoginService $loginService,
        OauthProviderFactory $oauthProviderFactory
    ) {
        $this->auth = $auth;
        $this->loginService = $loginService;
        $this->oauthProviderFactory = $oauthProviderFactory;
    }

    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next = null)
    {
         $provider = $request->getAttribute('provider');
        $providerObj = $this->oauthProviderFactory->newInstance($provider);
    }
}  
```

When a factory comes I guess probably this can get rid of creating different factories with a generic factory of di.

Or do you have any better suggestion ?

Thank you

**Comment by glen-84** [comment]
> please for the love of all that is good, not make()

Agreed.

> Perhaps the thing to do here is lobby the container-interop folk to add a newInstance() method to a 2.0 version of the interface.

I'll see if I can get into contact with one or two of the C-I guys tomorrow.

> I must warn, though, that I expect it to be a difficult process, as creating a new instance is a relative complex thing

Well, I think it's already implemented by a number of containers (see the list [here](https://github.com/container-interop/container-interop/issues/44)), but we'll have to see what they think.

**Comment by glen-84** [comment]
@pmjones,

C-I are not interested in defining the behaviour of `has`/`get`, so I've closed that [PR](https://github.com/container-interop/container-interop/pull/65).

They're also not interested in [factory](https://github.com/container-interop/container-interop/issues/44)/[invocation](https://github.com/container-interop/container-interop/issues/43) interfaces unless there is clear demand from framework and library authors.

This means that I have two main options:
1. Rely on an implementation, and use something like `newInstance` directly.
   - I was really hoping to avoid this.
2. Utilize your [proposed](https://github.com/auraphp/Aura.Di/issues/116#issuecomment-185303365) solution, which will allow me to use `has` and `get` in a (mostly) interoperable way.
   - Even though the semantics are slightly off, this might be the better option for now.

Are you still willing to provide that solution (i.e. implement `$di->newInstanceFactory()` with `has` and `get` methods)?

**Comment by glen-84** [comment]
@pmjones Have you had any time to think about this more? Please let me know if the proposed solution is still on the cards.

**Comment by glen-84** [comment]
I guess I'll have to go with plan C then. :disappointed:

**Comment by pmjones** [comment]
Seeing your evolution in how to think about this problem, there may actually be a solution already in place.

Given that (1) you want to create a new instance of an object, and (2) I think passing around the container itself is a bad idea, then (3) you might call `$di->getInjectionFactory()` and pass _that_ around. Calling `$injectionFactory->newInstance($className)` will create new instances for you, honoring all the params and setters from the container config. (It's what the Container uses itself to create new objects.)

Thoughts?

**Comment by glen-84** [comment]
The problem is that I wanted to use something that was not implementation-specific. I might as well just use `newInstance` directly, if I am forced to rely on a specific implementation.

`has`/`get` would be fine for ZSM & PHP-DI, but Aura does not behave the same way as PHP-DI with regard to "auto-wiring".

There is also no common (CI) interface for a factory method, so I can't depend on that either.

If the proposed solution is off the cards, I will have to either:
1. Hard-code something to use `has`/`get` unless the container is Aura.Di.
2. Create some kind of adapter class that wraps Aura to make `has`/`get` behave differently.
3. Create some kind of interface/adapter to make all containers consistent WRT their factory method.

I'm really not sure which direction to take at this point. I will have to think about it more when I have a clear mind.

**Comment by pmjones** [comment]
Yes, you do have kind of a tough requirement, since you want to standardize on a non-implementation-specific interface.  If you don't mind, then, I'd like to close this ticket for now; if after you have cleared your mind you feel it necessary to reopen it for discussion, then I'm fine with that.

**Comment by glen-84** [comment]
I'll close it. I have no choice but to hack something together. :disappointed:
