### ISSUE TITLE
Lazy Modify for newInstance ?

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Di#122]
I think I want to be able to tell the container to call a method multiple times
with different values (ie. I cant just use `setters`) as some kind 'modify'
step, but I dont want to have to do in the actual `modify` step of the
configuration, because I don't want to need to do all that stuff, until the
object is required.

Perhaps this is out of scope and I'm confused?
Am I wrong to want this functionality?

Example of the basic thing I want to happen:

``` php
<?php
// say Service implements SplSubject
$service = new SplSubjectService();
$service->attach(new ObserverA);
$service->attach(new ObserverB);
```

One way I could do it now, but it _requires_ services, ie. I couldn't do it if
I wanted it called for every instantiation of said object. And, it's _not lazy_,
and would need to happen all the time.

``` php
// container config
public function define($di)
{
    $di->set('service', $di->lazyNew(Service::class));
}

public function modify($di)
{
    $service = $di->get('service');
    $service->attach($di->newInstance(ObserverA::class));
    $service->attach($di->newInstance(ObserverB::class));
}
```

I guess I could do it `lazy`, but would again _need services_:

``` php
$di->set(
    'service',
    $di->lazy(
        function () use ($di) {
            $service = $di->newInstance(Service::class);
            $service->attach($di->newInstance(ObserverA::class));
            $service->attach($di->newInstance(ObserverB::class));
            return $service;
        }
    )
);
```

I dont know about nomenclature here, but something like this maybe?
Although, the 'keyless append' nature here seems to negate the intuatively
implied `removeModifier` method.

``` php
$di->addModifier(
    Service::class,
    'attach',
    $di->lazyNew(ObserverA::class)
);
```

Maybe adding some kind of `key` param would help that, but seems possibly gratuitous.

``` php
// Maybe name the step so there's a key??
// This seems weird to me though.
$di->modifiers[Service::class]['add observer b'] = [
    'attach',
    $di->lazyNew(ObserverB::class)
];
// remove modifier
unset($di->modifiers[Service::class]['add observer b']);

```

or maybe some way to pass an object to a function for modification after?

``` php
$di->modify(
    Service::class,
    function ($service) use ($di) {
        $service->attach($di->newInstance(ObserverA::class));
        $service->attach($di->newInstance(ObserverB::class));
        return $service;
    }
);
```

Thoughts?

**Comment by pmjones** [comment]
> Perhaps this is out of scope and I'm confused?
> 
> Am I wrong to want this functionality?

For good or bad, there are some objects that need to be set up using multiple calls to the same method. However, coming up with a configuration process for that is kind of tough, especially when you want to support replacing, overriding, and appending-to that set of method calls. (We support replacing, overriding, and appending-to in params and setters, so it seems reasonable to do that for multiple calls to the same method as well.) I've tried a couple of times and have not found a satisfactory solution.

My guess is that if you are writing the class yourself, there's some way of passing an array of params to the constructor that will call the needed methods itself.

Alternatively, especially if you are not writing the class yourself, you can still wrap the creation logic in a factory, and pass an array of params to the factory, and let the factory apply those params to the methods to be called.

Hope that all made sense.

**Comment by jakejohns** [comment]
Yup, factory makes sense. Thanks!
