### ISSUE TITLE
Consider aliasing old Config to new ContainerConfig

### ISSUE THREAD

**Issue by pmjones** [auraphp/Aura.Di#124]
Consider adding `class_alias('Aura\Di\ContainerConfig', 'Aura\Di\Config')` to the package somewhere, to ease use of 2.x configs with 3.x. Alternatively, create an alias class explicitly.

**Comment by compwright** [comment]
+1

**Comment by harikt** [comment]
Did you considered this ?

**Comment by pmjones** [comment]
Still considering. :-)

**Comment by pmjones** [comment]
Since this was mostly a 2.x to 3.x conversion issue, and since I've not run into it any more, I am closing this. It's trivial to add to one's own config system, and I want to avoid aliasing something in a non-obvious way.
