### ISSUE TITLE
Allow Di to load trait setters

### ISSUE THREAD

**Issue by galactic-void** [auraphp/Aura.Di#13]
Allow the use of setters from traits.

For example:

```
$di->setter['Aura\Foo\ATrait'] = [
    'setObject'  => new Class,
];
```

From my limited testing and understanding of Aura.Di it seems to be simple enough.

I added this just after `merge the setters` comment in the `fetch` method of `Config.php`

```
$uses = class_uses($class);

foreach ($uses as $use) {
    if (isset($this->setter[$use])) {
        $unified_setter = array_merge($unified_setter, $this->setter[$use]);
    }
}
```

**Comment by harikt** [comment]
Hey @galactic-void nice to see you :) .

**Comment by pmjones** [comment]
If you can provide this as a pull request with an associated test, that would be awesome.

**Comment by galactic-void** [comment]
I've made the pull request. it seems to be a simple enough feature to implement unless I've missed something.

The changes: https://github.com/galactic-void/Aura.Di/commit/64a906b7eefdda771c4df74a8ac4e9bcf47c6f93#src/Aura/Di/Config.php

@harikt good to see you too. Its nice to have some free time.

**Comment by harikt** [comment]
@galactic-void I have commented on your PR .

Currently all activity happening at develop branch . Please have a look into 

http://auraphp.github.com/2012/07/13/contributing-to-aura-project/

Thanks for it.

**Comment by harikt** [comment]
This is merged . So closing the issue. @pmjones please do merge the master to develop :) .

**Comment by pmjones** [comment]
Merged to develop and pushed.

**Comment by galactic-void** [comment]
@harikt Sorry about that thanks for the update

**Comment by harikt** [comment]
:) no issues.
