### ISSUE TITLE
PSR-11

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Di#144]
Hi @pmjones , 

As you may be knowing PSR-11 has passed https://twitter.com/mwop/status/831537408361512962 .

How are we planning to integrate psr-11 to version 3 or is there a version 4 you are thinking when we extend the interface ?

**Comment by laurensV** [comment]
Interested in PSR-11 support as well :)

**Comment by harikt** [comment]
Hi, 

I have initiated https://github.com/auraphp/Aura.Di/pull/145 for https://packagist.org/packages/container-interop/container-interop already requires https://packagist.org/packages/psr/container . So we are not breaking anything.
