### ISSUE TITLE
Each will be deprecated in PHP7.2

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Di#150]
See [the current reflector](https://github.com/auraphp/Aura.Di/blob/3.x/src/Resolver/Reflector.php#L132) and the PHP [documentation](http://php.net/each). I'll do my best to create a PR for it.

**Comment by harikt** [comment]
@frederikbosch see https://github.com/auraphp/Aura.Di/pull/148 . May be I close this issue for that is also the same. We need to fix the failing tests :-( .
