### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Di#153]
https://github.com/auraphp/Aura.Di/compare/3.2.0...3.x

There's been a couple of things added here since the last release: #143, #146.

**Comment by harikt** [comment]
Sure, we can do .

One more PR waiting https://github.com/auraphp/Aura.Di/pull/151 . 

Do you have any inputs on it ?

I can do a release tomorrow or day after tomorrow. 

If you need it today for the other I can try.

**Comment by jakejohns** [comment]
No rush. I just noticed a recurring theme of projects I have requiring dev versions of packages :-/ so I thought I'd call out the major ones. I can wait on #151. I've looked at it a few times, but honestly, it hasn't come up for me in a project yet, so I don't have thoughts really.

Thanks!

**Comment by jakejohns** [comment]
Still waiting on #151 ... :-/

**Comment by harikt** [comment]
We will do a release.

**Comment by harikt** [comment]
When I was doing a release (13 hours back), I got a sad news that my uncle passed away.

This release [3.3.0](https://github.com/auraphp/Aura.Di/releases/tag/3.3.0) is for history and for his ( Kommadath Sarvadamanan ) remembrance by the world.

**Comment by jakejohns** [comment]
My condolences

**Comment by pmjones** [comment]
@harikt Somehow I missed this news. My condolences. Hope you and your family are doing OK.
