### ISSUE TITLE
PHPUnit 6 upgrade?

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Di#158]
Would you accept a PR to upgrade the PHPUnit tests to use version 6 syntax?  If so, on which branch should it go?

**Comment by harikt** [comment]
I don't think we can support it for Aura.Di supports php 5.5 https://github.com/auraphp/Aura.Di/blob/f676b38a0d1c3b0d7897b0a082f4811eb8b08faa/composer.json#L21 .

phpunit 6 supports only 7.x : https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0
