### ISSUE TITLE
PHPStorm plugin

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Di#162]
I'd love to have a PHPStorm plugin that autocompletes the defined services in the container. There is a [plugin for Symfony](https://confluence.jetbrains.com/display/PhpStorm/Working+with+the+Service+Container+-+Symfony+Development+using+PhpStorm). Is anyone aware if there is one for Aura DI? Furthermore, if not, does anyone know how to create such a plugin?

**Comment by djmattyg007** [comment]
If you're using your DI container properly (ie not as a service locator), this shouldn't be necessary. You shouldn't need to pull anything out of the container manually, meaning there's no need for specialised autocompletion.

**Comment by frederikbosch** [comment]
I am not using it as service locator. I am not using a service locator at all. Since I am using a plugin system, each plugin configures its own injections and dependencies.

Because of this separation, I would love to have auto completion, because I not always remember what the name of a service is that is defined in another (dependent) plugin or in the general boot process.

**Comment by frederikbosch** [comment]
Those interested have a look at: https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata.

@pmjones I also saw your question on Twitter. It should be fairly to create `PHPSTORM_META` for Atlas.
