### ISSUE TITLE
Wrong resolution of variadic parameters

### ISSUE THREAD

**Issue by denfil** [auraphp/Aura.Di#164]
Here is the code example:
```php
class Test {
    public function __construct(...$items) {
        print_r($items);
    }
}

class Config extends Aura\Di\ContainerConfig {
    public function define(Aura\Di\Container $di)  {
        $di->params[Test::class][] = 'one';
        $di->params[Test::class][] = 'two';
        $di->set('test', $di->lazyNew(Test::class));
    }
}

(new Aura\Di\ContainerBuilder())
    ->newConfiguredInstance([Config::class])
    ->get('test');
```
Expected output is `Array ( [0] => one [1] => two )`
but actual output is `Array ( [0] => one )`

**Comment by harikt** [comment]
Try 

```php
$di->params[Test::class]['items'][] = 'one';
$di->params[Test::class]['items'][] = 'two';
```

or

```php
$di->params[Test::class]['items'] = [ 'one' ,'two'];
```

**Comment by denfil** [comment]
@harikt it's not the same behaviour I want to get, because
`__construct(...$items)` is not the same as `__construct(array $items)`

You see, in my example constructor should get **two** parameters of type **string**
`new Test('one', 'two')`,
but in your solution it will get **one** parameter of type **array**
`new Test(['one', 'two'])`

**Comment by harikt** [comment]
I get you now. If you can send a patch I ll look into it.

**Comment by marcusjhdon** [comment]
I've also experienced this issue, so I decided to create a patch. The approach I've taken is to treat the parameter as an array, then to expand it just before object instantiation using the (cached) reflection info. 

Please consider applying this patch to the main branch soon, so I can avoid having to maintain a custom fork. Thanks.

[variadic-patch.txt](https://github.com/auraphp/Aura.Di/files/2089656/variadic-patch.txt)

**Comment by harikt** [comment]
Hey @marcusjhdon ,

Could you send a PR, it may be helpful.

Thank you.

**Comment by marcusjhdon** [comment]
Done: https://github.com/auraphp/Aura.Di/pull/167

**Comment by harikt** [comment]
Fixed in https://github.com/auraphp/Aura.Di/pull/167 . Will shortly push the new tag.

**Comment by harikt** [comment]
Sorry the issue looks not fixed yet. So re-opening it.

**Comment by harikt** [comment]
#167 actually fixed the issue with constructor params, but not for setter. The example I copied from here was wrong and that made me think that failed. Currently things are on 3.x branch. I am not tagging for now for I am still debating with myself whether it should be moved to the `Resolver::resolve` method.

**Comment by frederikbosch** [comment]
I would suggest that this functionality can be achieved by using a mutation as in PR #176 or by using factory and that the library should not resolve variadic arguments for setters.

**Comment by frederikbosch** [comment]
Since #176 is merged into master, one can choose to mutate an object and therefore call methods with multiple arguments and/or variadic arguments.
