### ISSUE TITLE
No mention of `Blueprint` in migration doc

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Di#189]
I was just migrating https://github.com/radarphp/Radar.Adr to use Aura.Di release 4.0.0.  My primary purpose was similar to much of the Aura.Di 4.x work: updating PHP to 7.1 or better, and using a newer PHPUnit.  I ran into problems when all of the unit tests failed when calling `Aura\Di\Injection\InjectionFactory::newInstance()` because of the signature change to require a `Blueprint` instance.  However, this BC break change is not mentioned in the `migrating.md` document.

I can attempt to write something about this and make a PR.  However, I'd like to be sure I am not making some mistakes in understanding all the changes.

**Comment by frederikbosch** [comment]
@cxj `Blueprint` should be internal. I don't have any mentions of it in my client code. Why are you using `InjectionFactory` directly?

**Comment by cxj** [comment]
I'm just updating the code that Paul M. Jones originally wrote in Radar.Adr, which seems to have its own [`Resolver`](https://github.com/radarphp/Radar.Adr/blob/85046fc14113d7072fe91e0dc152e91d2ba9e5bf/src/Resolver.php#L53) which wraps the Aura.Di `Resolver`.  I'm not sure why Paul did it that way.

That said, there is a [PR against Radar.Adr](https://github.com/radarphp/Radar.Adr/pull/32) to remove Radar's Resolver and just use Aura.Di's `ResolutionHelper` as a replacement.  Maybe that is ultimately a better solution.

However, `newInstance()` is a `public` function, so is it not conceivable that some user of Aura.Di might be using it directly in a similar fashion as Radar.Adr?

**Comment by frederikbosch** [comment]
Fixed by #190
