### ISSUE TITLE
4.1 tag for PHP 7.4 support?

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Di#194]
Can we get a release tagged 4.1 (or ?) for the PHP 7.4 support?  Thanks!

**Comment by frederikbosch** [comment]
Why would you need that? There is no new code in the src folder, right?

**Comment by cxj** [comment]
It does seem the only relevant changes are to `composer.json` and to the `./tests` folder.  However, I have projects which use Aura.Di which I wish to modernize to use newer versions of PHPUnit.  Right now, when I run my unit tests, I get errors like this:
```
PHP Fatal error:  Declaration of Aura\Di\AbstractContainerConfigTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void ...
```
I can use `dev-master` to make that work, but for stable releases of my projects, I of course want to use only tagged releases of their dependencies.

Hope I've made sense to you.  Thanks.

**Comment by harikt** [comment]
Hey @frederikbosch ,

I think @cxj 's argument is valid. May be you can tag another release ?

**Comment by frederikbosch** [comment]
Done, tag is there. Thanks @cxj

**Comment by cxj** [comment]
Thank you very much!
