### ISSUE TITLE
PHP 5.3 support

### ISSUE THREAD

**Issue by jjok** [auraphp/Aura.Di#20]
It looks like the only new feature of PHP 5.4 used in this package is the short array syntax. How about changing back to the long syntax until support for 5.3 is officially dropped?

**Comment by jjok** [comment]
Hmmm... Ok. You've got trait stuff in there too...

**Comment by harikt** [comment]
Hey @jjok it is not possible. We have also `callable` type hint etc . See http://php.net/manual/en/language.types.callable.php .

So I am closing this issue. Why not move to 5.4 ?

Thank you.

**Comment by jjok** [comment]
Yeah, I'm finding more 5.4 stuff as I look through it. Thanks.
