### ISSUE TITLE
Resolver/AutoResolver.php relies on `ReflectionParameter::getClass()` which is deprecated in php 8

### ISSUE THREAD

**Issue by far-blue** [auraphp/Aura.Di#201]
Resolver/AutoResolver.php relies on `ReflectionParameter::getClass()` (line 60) which is deprecated in php 8.

There are a couple of suggested alternatives in the user contributed notes on php.net: https://www.php.net/manual/en/reflectionparameter.getclass

**Comment by frederikbosch** [comment]
Fixed in master, tag upcoming
