### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by frederikbosch** [auraphp/Aura.Di#208]
Since PHP8, attributes are a native feature in PHP. I would like to introduce them to this package.

```php
<?php
declare(strict_types=1);

namespace NS;

use Aura\Di\Attribute\Inject;

class MyService {
    public function __construct(
        #[Inject\Service('some.defined.service')]
        MyOtherService $service,
        #[Inject\Instance(SqlRepository::class, ['charset' => 'utf8'])]
        RepositoryInterface $repo,
    ) {
    }
}
```

Is this something someone is highly against?

**Comment by harikt** [comment]
I am not against, but I am not using Attributes that much.

**Comment by frederikbosch** [comment]
Okay, thanks for your reply. In that case I will continue working on it.

**Comment by harikt** [comment]
I closed this because we already have a PR. Any reason you re-opened this ?

**Comment by frederikbosch** [comment]
Ah ok. I always leave issues open while the PR is not merged. Closing again.
