### ISSUE TITLE
Convert class names to fully qualified names

### ISSUE THREAD

**Issue by MAXakaWIZARD** [auraphp/Aura.Di#23]
use Aura\Di\Container;
use Aura\Di\Forge;
use Aura\Di\Config;

$di = new Container(new Forge(new Config));

$this->di->setter['Foo\Bar']['setBaz'] = $di->lazyGet('Baz');
$this->di->set('foobar', $this->di->lazyNew('\Foo\Bar'));

setBaz will not be called upon \Foo\Bar instantiation, because setter was defined as Foo\Bar. Same with constructor params definitions.
I think we should convert all class names to fully qualified names internally:
1) newInstance
2) param
3) setter
4) lazyNew

**Comment by pmjones** [comment]
Also a good call. spl_autoloader strips the leading namespace separator; we can do the same here.

**Comment by MAXakaWIZARD** [comment]
Ok, I'll do it

**Comment by pmjones** [comment]
This turns out to be non-trivial; looks like we need something that modifies the params/setter keys along the way. That means extending or replacing ArrayObject in the Config class.   Working on it now.

**Comment by pmjones** [comment]
This is surprisingly tricky. Would we consider it an option to make this a "documentation issue" instead of a code one?

**Comment by MAXakaWIZARD** [comment]
Well yes, I also replaced ArrayObject in Config, but not finished yet.

**Comment by pmjones** [comment]
Cool.  I'll wait to see your changes.

**Comment by pmjones** [comment]
Hey @MAXakaWIZARD , any progress on this? It strikes me as pretty involved. Let me know if (1) you want to keep working on it, and (2) if not, we can make it a documentation issue.

**Comment by MAXakaWIZARD** [comment]
Well, yes, it is very tricky.
$di->setter['Example\Package\Foo']['setDb'] here we have multidimensional array, and there are some issues with overriding standard behavior.

**Comment by MAXakaWIZARD** [comment]
But please let it hang a little more. I think there are no reasons to hurry...

**Comment by pmjones** [comment]
Fine with me. :-) I mention it only because the effort seems high in relationship to the reward.

**Comment by CMCDragonkai** [comment]
Can you explain what effect you are trying to achieve?

**Comment by MAXakaWIZARD** [comment]
It is explained in first post. Idea is - prevent possible errors in objects definition.

**Comment by pmjones** [comment]
@MAXakaWIZARD -- any progress here? If not, I'd like to close the ticket, just so that it doesn't keep popping up in my review.

**Comment by pmjones** [comment]
Not to be impatient, but I myself have not had this particular problem, and it appears relatively uncommon. As it has lingered for many months without a PR, I am closing this ticket. If you come up with a PR for it, please feel free to reference this ticket and I'll reopen it as appropriate.
