### ISSUE TITLE
Container error detection

### ISSUE THREAD

**Issue by MAXakaWIZARD** [auraphp/Aura.Di#24]
For instance,
use Aura\Di\Container;
use Aura\Di\Forge;
use Aura\Di\Config;

$di = new Container(new Forge(new Config));

$this->di->setter['Foo\Bar']['setBaz'] = $di->lazyGet('Baz');
$this->di->set('foobar', $this->di->lazyNew('Foo\Bar'));

If Foo\Bar doesn't have setBaz method, just nothing happens. It can be very hard to cope with such hidden bugs.
Shouldn't we have some error detection code? For instance, throw exception 'Setter method setBaz not found in Foo\Bar class' etc

**Comment by pmjones** [comment]
Good call. We can add a check in the creation code.

**Comment by MAXakaWIZARD** [comment]
Ok, I'll do it

**Comment by pmjones** [comment]
Fixed in https://github.com/auraphp/Aura.Di/commit/a654c9ea42f74b54739ed79afb3d0ebe3064fa47
