### ISSUE TITLE
Extra lazy services

### ISSUE THREAD

**Issue by MAXakaWIZARD** [auraphp/Aura.Di#27]
I think it is a must-have feature for DI container.

``` php
$this->di->set('foobar', $this->di->lazyNew('\Foo\Bar'));

//\Foo\Bar is instantiated here, even if we do not call any method on service object $foobar
$foobar = $this->di->get('foobar');
```

The point is, we can instantiate lightweight proxy instead of service. Proxy has __get, __set and __call hooks, and it will create real service object when it is firstly accessed.

I think we can achieve this by introducing extraLazyNew method or something like that.

**Comment by pmjones** [comment]
Hi @MAXakaWIZARD --

Your examples make me think you are using the DI container as a service locator; i.e., using `$this->di` as if it's been injected into another object.  That is to be avoided. ;-)

One of the problems with a generic Proxy object is going to be when a param has been type hinted. If a constructor is hinted to `Foo $foo`, and you pass a `Proxy`, it won't work. As such, anything that needs to be proxies needs to wrap the thing it's a proxy for, which means no generic proxies, which makes a generic extraLazyNew() method redundant.  If you need a proxy, write it, and pass _that_ as the param.

This is just all off-the-cuff. Hope that makes sense, and let me know if I'm missing something.

**Comment by MAXakaWIZARD** [comment]
Nope, I also use Aura.DI as dependency injection via constructor and setters

**Comment by pmjones** [comment]
/me nods

The other comments about proxies still stand, though. If you have some examples or a patch I'd be happy to review.

**Comment by MAXakaWIZARD** [comment]
How do you then use it?

**Comment by MAXakaWIZARD** [comment]
Maybe we could implement extra lazy services and let users choose, told them about pitfalls when using proxies. Symfony DI Container already has that feature.

**Comment by pmjones** [comment]
@MAXakaWIZARD I have not given this much further thought, and I have heard no others make a request for this kind of thing. If you end up implementing a generic proxy system for the Aura DI container, I'll be happy to review it, but in the mean time I'm closing this ticket. We can re-open it in the future if necessary.

**Comment by F21** [comment]
I was just reading about this in [symfony](http://symfony.com/doc/master/components/dependency_injection/lazy_services.html).

I think it would be better if a bridge can be built to use https://github.com/Ocramius/ProxyManager rather than reimplementing the whole thing. I have not had a chance to investigate, but does Aura.Di provide some way we can hook in during object instantiation and drop in a proxy?
