### ISSUE TITLE
Set default concrete class to interface for fully automatic dependency resolution

### ISSUE THREAD

**Issue by adriengibrat** [auraphp/Aura.Di#29]
This could be achieved by adding a $concrete ArrayObject property to Config, where we could store interface to concrete binding, i.e. [interfaceName => concreteName], and this would be made available from Di like this:
$di->concrete['interfaceName'] = 'concreteName';

Then in Config::fetch, when building the $unified_params, whe could replace interfaces by concrete class names.

Is this something you would find usefull for Aura.Di? May I propose a PR

P.S. it's the Phil Bennett benchmark that made me realize this features was missing in Aura.Di ...

**Comment by harikt** [comment]
@adriengibrat I wonder whether making any change will break the existing api for v1 ( dev-develop ) .

v2 (dev-develop-2) has not been released. And there is also some discussions going on ( "Aura.Di v2 and inheritance" ) at google groups https://groups.google.com/d/msg/auraphp/OBbGxJvZcho/KSip3TAek4gJ 

That said, you can always send a PR with the changes and it will be reviewed and merged if found satisfactory.

Thank you, and this seems to be your first issue to aura.

**Comment by adriengibrat** [comment]
Hello @harikt ,
Yes it i my first issue, more a feature request ;)
I was thinking about adding this to Aura.Di v2, has it is the default branch, but this should not break anything in the API (nor v1  nor v2).
Thanks for the google groups discussion link. Interesting discussion. Checking inherintance may be long since it's recursive, concrete binding isn't.
Plus, I think it encourage a good practice: using interface as type hints.

I'll end a PR, as soon as I got some spare time!

**Comment by harikt** [comment]
cool.

**Comment by pmjones** [comment]
Per my comment in #33, if you want to present a separate PR regarding an explicit way of mapping concrete instances to use for specific interface type hints (whether as services or new instances) I'd be happy to review it.
