### ISSUE TITLE
no constructor & setter injection : ReflectionException

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.Di#38]
Hello,
When we have a class with no constructor method but we are using setter dependency on it (or in my case the child's class), an exception is thrown 
exception 'ReflectionException' with message 'Class XXX\YYY\ZZZ does not have a constructor, so you cannot pass any constructor arguments' in .../aura/di/src/Container.php:419
Stack trace:
#0 .../library/aura/di/src/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#1 ... Aura\Di\Container->newInstance('XXX\YYY\ZZZZ')

in this class ZZZ implements an interface with a setter  but don't have constructor method.

**Comment by Grummfy** [comment]
Sorry, probably link to an old version of php (PHP 5.3.3-7 with Suhosin-Patch (cli))
Work on local version (PHP 5.3.26 (cli))

**Comment by pmjones** [comment]
@Grummfy I am checking on it right now.

**Comment by pmjones** [comment]
@Grummfy I added a test for this in v1 develop branch, and it appears to work OK here. I think it's just the older PHP version that is the problem. If you find otherwise, please reopen this issue.
