### ISSUE TITLE
Honor Interfaces

### ISSUE THREAD

**Issue by pmjones** [auraphp/Aura.Di#39]
Interface setters, and maybe params, should be honored by DI.

http://colabti.org/irclogger/irclogger_log/auraphp?date=2014-03-12#l144

**Comment by harikt** [comment]
some more discussion http://colabti.org/irclogger/irclogger_log/auraphp?date=2014-03-13#l43

**Comment by ghost** [comment]
I don't know if constructor injection would be the way to go for making the DI container work with interfaces and traits, but setter injection would be really handy.

I probably don't have a lot of time personally to try this and do a PR, but if anyone has a hint on where I should start the code search, I'd appreciate the help :)

**Comment by pmjones** [comment]
Fixed by #42.
