### ISSUE TITLE
Alternate overriding model wanted

### ISSUE THREAD

**Issue by chelmertz** [auraphp/Aura.Di#4]
I'm thinking the `Container::get($key)` could be elaborated to `Container::get($key, $parameters = array())` where `$parameters` is the `$di->params[...]` in http://auraphp.github.com/Aura.Di/#variation_4a_override_class_constructor_params.

That way, I can config some stuff without effecting the main config for `$key`.

Let me know if I'm way off or going about this the wrong way :)

Cheers

**Comment by pmjones** [comment]
Hi chelmertz -- The difference here is that get() works with a service that has already been defined, and newInstance() as used in the override is for creating a new object.  When we get(), we want to get the service as defined and shared with others, not get a new instance of that service object with perhaps some different params.  Hope that makes sense.
