### ISSUE TITLE
Aura Input Options is getting the closure

### ISSUE THREAD

**Issue by ghost** [auraphp/Aura.Di#40]
Paul,

Correct me if I'm wrong, but today at work I saw something that might be wrong.
The code:

``` php
<?php

$di->params['Aura\Input\Form'] = [
   'builder' => $di->lazyGet('builder'),
   'filter' => $di->lazyGet('filter'),
   'options' => [
         'helperList' => $di->lazyGet('helperList')
   ]
];

```

The **options** key in the constructor injector will receive an array containing N available options, but the **lazyGet('helperList')** returns the callable. Shouldn't it be returning the object? 

In this example I've set the params to Aura\Input\Form, but locally it's mapped to a final Form class.

**Comment by harikt** [comment]
`lazyGet` always will get callable. Instead use `lazyNew` here.

**Comment by harikt** [comment]
aah there is another thing I am seeing. It may also depends on how your `lazyGet` is asked to call.

Example I tried 

``` php
class Example
{
    public function __construct(Foo $foo) 
    {
        echo get_class($foo);
    }
}

class Foo
{
}

$di = new Container(new Forge(new Config));
// 1 ) $di->set('lazyfoo', new Foo);
// 2 ) $di->set('lazyfoo', $di->lazyNew('Foo'));
$di->params['Example'] = [
    'foo' => $di->lazyNew('Foo')
    // for 1, 2 comment the above line and uncomment the below line
    // 'foo' => $di->lazyGet('lazyfoo')
];
$di->newInstance('Example');
```

**Comment by ghost** [comment]
Hari,

In our case, the helperList is a service, defined this way:

``` php
$di->set('helperList', function() use ($di) {
   return $di->newInstance('app\services\HelperList');
});
```

We use **lazyGet** a lot with our constructor params and we always get the reference, except at this time.

The **lazyNew** in this case, will return an instance, but we always define our services using the way described above, in case we need to do any setup before returning the instance.

**Comment by harikt** [comment]
I feel `lazyGet` is working as expected. Ping @pmjones for further details.

**Comment by pmjones** [comment]
I think the problem here is that the 'options' key is presented as an array, and the DI container does not descend to array elements to resolve lazy objects. If you modify it to be something more like this ...

```
'options' => $di->lazyGet('helperList')
```

... then the form `$options` will be your `helperList` service object.

Let me know if that helps.

**Comment by ghost** [comment]
Paul and Heri, sorry for the late update.
Yes, using with arrays doesn't work as expected and we've already eliminated the array.

Thanks!

**Comment by pmjones** [comment]
:+1:

**Comment by harikt** [comment]
@ramirovjr :+1:  .

NB : H **A** RI ;)
