### ISSUE TITLE
Auto resolution or args based on namespace

### ISSUE THREAD

**Issue by mbrevda** [auraphp/Aura.Di#47]
There seems to be a lot of boilerplate necessary to configure each class for Di. Perhaps the argument namespace can be examined and an object passed based on the namespace expected. While this would require _some_ configuration on the Di side, it would greatly eliminate the amount of setup needed.

[Relevant irc logs](http://colabti.org/irclogger/irclogger_log/auraphp?date=2014-06-24#l207) (19:27-19:34)

**Comment by harikt** [comment]
@mbrevda there is a sister project which uses Aura.Di by @koriym https://github.com/koriym/Ray.Di . It resolves auto resolution of stuffs if you need.

Thanks

**Comment by pmjones** [comment]
Oooo! Yeah that might be the right thing to do here. @koriym has done very good work in that regard. @mbrevda take a look at Ray.Di and tell me if it suits your needs.

**Comment by koriym** [comment]
Thanks @harikt @pmjones :)

**Comment by harikt** [comment]
/me bows . @koriym you are welcome dude.

**Comment by pmjones** [comment]
In light of of the existence of Ray.Di, I am not eager to set up auto-resolution in the core Aura.Di package. We can revisit this later if needed.
