### ISSUE TITLE
Aura.DI requires the method to be formally defined to use it as a setter

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Di#48]
Setters come in all forms, including "magic" setters that make use of __get and __set. Aura.DI v1 doesn't support this, because it checks that the method exists, which a magic setter has no existing method.

**Comment by pmjones** [comment]
Can you think of a way to check if the method exists when it only works via __call() ? (If we don't check, then we have greater opportunities for errors in setup.)

**Comment by brandonsavage** [comment]
Unfortunately I think that's the whole point of __call(), is to let the
logic be executed at runtime.

**Comment by pmjones** [comment]
/me nods

I have a hard time thinking of a solution, then, other than removing the error-checking and letting errors happen at newInstance() time (i.e. when the object is created). And removing the error checking will break the existing tests IIRC.

Your thoughts?

**Comment by pmjones** [comment]
At this point I see no option other than to note that __call() will not work in this situation. It will have to be defined-setters only.
