### ISSUE TITLE
Lazy Loading of DI Params

### ISSUE THREAD

**Issue by jwoodcock** [auraphp/Aura.Di#52]
Conversation can be found here: 
http://colabti.org/irclogger/irclogger_log/auraphp?date=2014-07-22#l212

Thanks @harikt, great tool.

**Comment by harikt** [comment]
@jwoodcock Next time good to point to colabti.org where we have the logs :) .

http://colabti.org/irclogger/irclogger_log/auraphp?date=2014-07-22#l212

**Comment by jwoodcock** [comment]
@harikt But that also picks up all the stupid things I said, which were a lot. ;-)

**Comment by jeremykendall** [comment]
Why is there no :star: or :+1: button for issue comments?  Because @jwoodcock. :wink:

**Comment by jwoodcock** [comment]
@jeremykendall I guess github just assumes you're actually doing work in these things. I hardly know the meaning of the word.

**Comment by harikt** [comment]
@jwoodcock what I was trying to point was there is no name who said and who is saying in the conversation.

So hard to see what is going on. 

If you look at logs it has more options like get raw contents, get html contents only ;) . Also search . wow :) .

@jeremykendall no we have star and like button from you  :-) .

**Comment by jeremykendall** [comment]
PLUS ONE

/me now stops rudely threadjacking Aura's issue tracker ...
