### ISSUE TITLE
Feature: explicit resolution only setting

### ISSUE THREAD

**Issue by Beanow** [auraphp/Aura.Di#68]
In our project so far we've had a load of bugs that were caused by auto-resolution of the DI.
These are generally hard to detect bugs like mysterious class instances that get the wrong constructor parameters even though the code looks fine.

For example:
Changing the name of a parameter in the constructor, but not in the config.

This causes the class to be auto-resolved and the entry in your config will be ignored completely. It looks at first glance that you declared the parameter, but in reality it is auto-resolved.

My preference would be that this throws two exceptions.
One that the required parameter is not explicitly defined.
And one for an unused entry in your config.

Hence I would like to disable auto-resolving completely and force the use of explicit definitions only.

**Comment by cordoval** [comment]
Why not removing it altogether

**Comment by Avaq** [comment]
It seems this feature was opposed when proposed in #47 and [in IRC](http://colabti.org/irclogger/irclogger_log/auraphp?date=2014-06-24#l207) yet was still implemented a few months later in e3bc360ad56267cbb19f29faefefc8ff668bec7b. I too would like to see the possibility to disable this feature at the least. It's causing significant frustration. My only frustration with Aura so far. :)

**Comment by cordoval** [comment]
yeah i think imo it was a slip, one of the maintainers @harikt likes it. I come running away from symfony because of this type of magic, not that there is that already on symfony but you get me. Maybe let's try to decouple that into a component rather than making it even optional on the DI. But i could be wrong, let's wait for @pmjones

**Comment by Avaq** [comment]
Harikt himself says "[seems like a curse now](https://groups.google.com/d/msg/auraphp/aeaEV-5Q76A/ceAegmc2j5sJ)" about the feature. I think decoupling it into a separate package somehow is a great idea.

**Comment by cordoval** [comment]
:+1: for removing now that I see this

**Comment by pmjones** [comment]
First, please accept my apologies. I should have left the auto-resolution in a beta state for longer before committing it into a stable release. I should have maintained my conviction about the drawbacks of auto-resolution, as even the folks who wanted now don't like it.

But there's a problem with making it optional. Libraries that are built with auto-resolution in mind now depend on it to be there for operational purposes. That means a project that turns it off would make that library look broken, when it was just an option setting. In addition, removing it entirely seems like a BC break at this point.

Any thoughts? I'd rather not release a 3.0 just to remove the auto-resolution, but if it's that big a problem, we can talk about it.

**Comment by pmjones** [comment]
Would it be enough to raise a notice (not a warning) that auto-resolution occurred? At least then it would be in the logs, and there'd be no BC break.

**Comment by Beanow** [comment]
For a removal strategy: I think you could decouple it, but keep it as a dependency to the DI itself. Including a deprecation warning that you must define this dependency yourself if you want to keep using it. Eventually removing the dependency.

As for warnings, I think these warnings do not make sense if you are actually using the auto-resolving as a feature. Maybe these warnings could be the result of a "strict mode" setting. Any serious library could modify their config files to use explicit definitions and not trigger warnings.

**Comment by pmjones** [comment]
So when you say "decouple it" do you have ideas on how to actually do that?

**Comment by Beanow** [comment]
I haven't looked at the internals of the DI, but my first thought would be something of a fallover mechanism. The auto-resolver can perhaps register itself to the DI as: in case you don't know, ask me first before throwing any errors. The DI can then talk to an interface of such a mechanism rather than an implementation. You could go crazy with this and implement whatever voodoo (download new packages, find a recomendation on google or what have you) you like that should happen in case the dependencies could not originally be resolved.

**Comment by pmjones** [comment]
That leaves us with a similar problem, though -- if library X expects auto-resolution, and it's not available under project Y, then the library "breaks."

**Comment by Beanow** [comment]
Certainly, so for the transition period, the DI package itself could depend on it to not break immediate dependencies. Later on though I suppose you will have to scale it down to specific packages. IE: limit the auto-resolving behaviour to the namespaces of packages that depend on functionality this only. Could be a composer extra variable with an array of auto-resolve namespaces, or similar.

**Comment by pmjones** [comment]
/me grimaces

That's all a bit ... convoluted. :-/

**Comment by cordoval** [comment]
keep it simple and just remove and go to 3.0, we learn from mistakes, and embrace a fearless meaning of semver

**Comment by Beanow** [comment]
For the moment yes, but eventually this means two lines in your composer file add the functionality for your package without affecting the others.

It's an issue in the first place that this behaviour is applied to all packages globally because of the huge amount of dependencies on the DI.

**Comment by pmjones** [comment]
@cordoval i hate the idea of bumping to 3.0 so fast, but you may be right :-/

**Comment by pmjones** [comment]
@Beanow tell you what -- if you can figure out a way to do what you're talking about, i'll be happy to review.

**Comment by cordoval** [comment]
it will teach other projects to avoid using the numbers for other purposes for once.  And will become the era of names for distros/releases. Like AuraPHP Lion, rather than aura 2.0. :blush:
But seriously we can just keep it very simple here.

**Comment by Beanow** [comment]
@pmjones I'm not sure I'll be in the position to do that for a while. Been spending a lot of time on the https://github.com/tuxion/doctrinerest library and deadlines are creeping closer :P

**Comment by pmjones** [comment]
/me nods

Yeah, we're all short on time. :-/

OK, for the record, I hear you on this. Auto-resolution makes for hard-to-track bugs and needs to be deprecated, removed, warned against, or otherwise noted as bad. I will address it as possible. Thanks in advance for your patience.

**Comment by Beanow** [comment]
Certainly, just out to help :]
I'm appreciating and learning from all the great work that went into the project already.

**Comment by harikt** [comment]
:) , no internet connection. So  you may not hear from me.

**Comment by harikt** [comment]
Have not looked how feasible it is ...

Idea is have a set a flag to auto resolve. 

`$di->autoResolve(true/false)` . A few problem already mentioned are 
1. If x package depends then there are issues when they are not specifically mentioned what to do

But may be specifically mentioning in docs will help ?

**Comment by pmjones** [comment]
@harikt I have taken your suggestion a top-level method, called setAutoResolve(), to turn on/off auto-resolution. It's in develop-2 now as of https://github.com/auraphp/Aura.Di/commit/4b61cf12b05293cd103f42088db6fcd8074bcdf5. The default setting is "true" to allow auto-resolution.

We should now:
1. Add this to the docs.
2. Note that Library/Bundle/Kernel authors **should not** develop with auto-resolution turned on, but that Project authors **may** do so (with the caveat that their stuff will be harder to debug).

This makes it possible to have one's cake and eat it too.

For everyone who has learned to hate auto-resolution: in your Project-level config file define() method, call `$di->setAutoResolve(false)` and your troubles should be over.

**Comment by pmjones** [comment]
As a side note, we can in a later release default to setAutoResolve(false) and go back to default explicit resolution. This might be considered a BC break so I'm not eager to do it.

**Comment by harikt** [comment]
@pmjones documenting about auto resolution to be turned off should work. At-least the developers should read the doc once ;-) .

**Comment by harikt** [comment]
Thank you @pmjones .
