### ISSUE TITLE
Add ability to pass additional setters to Forge::newInstance(), Container::newInstance() and Container::lazyNew()

### ISSUE THREAD

**Issue by kenaniah** [auraphp/Aura.Di#7]
The factory should accept an additional argument that would allow for additional setters to be passed to an object after construction. 

The api should look something like `Forge::newInstance($class, array $params = [], array $setters = [])`. The setters then applied to the `$class` instance after construction should be the combination of the setters found in the `Config` object along with the setters defined in the `$setters` parameter.

**Comment by pmjones** [comment]
Merged pull request; closing the ticket. Thanks!
