### ISSUE TITLE
Better identification on Aura\Di\Exception\ReflectionFailure 

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.Di#73]
When you have a Aura\Di\Exception\ReflectionFailure exception you can't always understand why. So add some message : 
- parameter missing (which one?)
- nothing defined
- class not found (display some autolaoding info?) (my issue in https://github.com/auraphp/Aura.Cli_Project/issues/12 )
- ...

**Comment by pmjones** [comment]
I agree that this would be useful. Any thoughts on how it should work?

**Comment by Grummfy** [comment]
Simply a message in the exception with what I explain before.

When you have a dependency failing, you need to understand what's builded (if possible where => a trace), what's wrong as detailed as possible, what's missing, what's been understand by Aura\Di.

So a message like this:
Aura\Di try to build/instanciate/... [classname, setter, ...] but have failed. The issue could come from [...]

**Comment by pmjones** [comment]
There's a long history here, but let it suffice to say that the custom ReflectionFailure exception isn't really needed any more. However, I have to keep it for backwards compatibility. What I'm going to do is capture the real ReflectionException message and push it into the custom ReflectionFailure exception message. Then you'll see something like 'Class Foo does not exist'.

**Comment by jeremykendall** [comment]
YES YES YES YES

**Comment by Grummfy** [comment]
thanks
