### ISSUE TITLE
IDE autocomplete

### ISSUE THREAD

**Issue by miladrahimi** [auraphp/Aura.Di#90]
I really care about IDE autocomplete but I tried the package and it seems IDE (In my case PHPStorm) doesn't recognize the objects data type, is there any solution?

**Comment by takyam-git** [comment]
I use `@var`.

``` php
/** @var \name\space\to\Foo $foo */
$foo = $di->get('Foo');
```

**Comment by miladrahimi** [comment]
Oh, you are right, thanks!
