### ISSUE TITLE
Should ContainerConfig not be an Interface

### ISSUE THREAD

**Issue by silentworks** [auraphp/Aura.Di#94]
Should this class not be an Interface since the methods are required if you were to create your own ContainerConfig for your project?

https://github.com/auraphp/Aura.Di/blob/3.x/src/ContainerConfig.php

**Comment by pmjones** [comment]
(/me ponders)

Originally I wanted to make sure the methods were implemented, so you wouldn't have to implement an empty one. But I can see the argument here. Send a PR that adds an interface, if you like, for auto-credit via Github.

**Comment by harikt** [comment]
@silentworks I was for abstract class.

Reason : If the `ContainerConfig` don't need to implement the `define` or `modify` it is already there. But  after thinking about this for sometime I feel `Interface` itself will be good so people don't forget they can change / implement this ;) / cc @pmjones

**Comment by pmjones** [comment]
I'm considering renaming `ContainerConfig` to `Provider` or something similar, since that seems to be the common name for container-configuration activity. I could add an interface at that time. Any thoughts on the name change?

**Comment by silentworks** [comment]
No objection here. I would just like an Interface. :-)

**Comment by acim** [comment]
Maybe ConfigProvider to be more precise?

**Comment by pmjones** [comment]
Fair enough. Tell you what, if you can send a PR for a ContainerConfigInterface, I can merge it, and then debate a name change later. Thanks for your patience.

**Comment by silentworks** [comment]
Well its not providing a Config, its providing a Service/Service setup, so just `Provider` or `ServiceProvider` will do.

**Comment by silentworks** [comment]
@pmjones yeah I will send a PR later in the week or if someone else gets to it before me.

**Comment by pmjones** [comment]
fixed in 9d70a2e
