### ISSUE TITLE
Docs for LazyGetCall (3.x)

### ISSUE THREAD

**Issue by jakejohns** [auraphp/Aura.Di#96]
Is ~~`lazyGetNew`~~ `lazyGetCall` omitted from docs intentionally?

**Comment by pmjones** [comment]
lazyGetNew() ?

**Comment by jakejohns** [comment]
im sorry. need more coffee... `lazyGetCall` is what I meant.

**Comment by pmjones** [comment]
Ah! No, its absence is not intentional. PR if you like!

**Comment by pmjones** [comment]
Fixed.
